### ISSUE TITLE
The parameter value RR is invalid.

### ISSUE THREAD

**Issue by bjl101501** [zf1976/vertx-ddns#3]

**Comment by zf1976** [comment]
问题是如何发生的？这表明域名记录值无效。

**Comment by bjl101501** [comment]
> 问题是如何发生的？这表明域名记录值无效。

![image](https://user-images.githubusercontent.com/82082262/133435616-6c3fae36-77dd-4042-b248-a2bf7daca8bf.png)
ok了，但是输入域名打不开.....

**Comment by zf1976** [comment]
我查了你域名ip已经同步到dns服务器上了啊，解析没啥问题，打不开是你服务有问题吧
