### ISSUE TITLE
在dnspod配置ipv6通过接口获取时，所配置的接口被ipv4的配置覆盖，配置无效

### ISSUE THREAD

**Issue by mmdjiji** [zf1976/vertx-ddns#5]
如题，经过测试ipv6和ipv4的接口不能分开设置，而是以ipv4为准，目前只测试了dnspod

**Comment by zf1976** [comment]
有截图吗，看一下日志或者设置图片

**Comment by zf1976** [comment]
![-3bd7f21b9eeffb17.jpg](https://user-images.githubusercontent.com/51810656/149644764-7e3add3b-e95c-4ec7-87b8-493031e27e9a.jpg)

**Comment by mmdjiji** [comment]
在我配置完ipv4之后，点进ipv6发现ipv6的配置变成了和ipv4相同。我手动修改ipv6配置但是保存后又恢复了修改之前的样子，初步判断可能是ipv6加载配置文件的时候加载的时候按照ipv4加载的。

![1.png](https://s2.loli.net/2022/01/16/jiXBqTObd9ef52A.png)

![2.png](https://s2.loli.net/2022/01/16/cQ75rbseqhgRCw3.png)

但是我莫名其妙卡了个bug，现在好像能正常解析双栈了，现在解析正常的情况下ipv6的web显示仍然与上图一致。

![log.png](https://s2.loli.net/2022/01/16/I5uoQbNgXdSmjtx.png)

**Comment by zf1976** [comment]
你安装的是那个版本啊，我之前遇过这个问题。docker安装是最新版暂时没有遇到问题。等会我复现一下给你答复

**Comment by mmdjiji** [comment]
```bash
sudo docker run -d -p 8081:8080 --name vertx-ddns --hostname vertx-ddns --network=host --restart=always -v vertx_ddns:/root/.vertx_ddns zf1976/vertx-ddns:debian
```
![ver.png](https://s2.loli.net/2022/01/16/ncEBtqQiwJ4S7AO.png)

**Comment by zf1976** [comment]
确实有这个问题，等下就可以修复了，到时候通知你，更新一下镜像就行了

**Comment by mmdjiji** [comment]
好的谢谢，您修复后自主Close issue就行了，哈哈哈，这玩意挺好用的，network调成host对v6的支持也不错

**Comment by zf1976** [comment]
> 好的谢谢，您修复后自主Close issue就行了，哈哈哈，这玩意挺好用的，network调成host对v6的支持也不错

已经修复了，等几分钟就可以拉docker最新版镜像了
