### ISSUE TITLE
phicomm-n1 小钢炮 Docker无法使用

### ISSUE THREAD

**Issue by Tamshen** [zf1976/vertx-ddns#6]
System : `Linux phicomm-n1 4.9.76 #1 SMP PREEMPT Thu Apr 11 20:39:46 CST 2019 aarch64 GNU/Linux`
System : `Linux version 4.9.76 (hacklog@arch-8700k) (gcc version 7.3.1 20180425 [linaro-7.3-2018.05 revision d29120a424ecfbc167ef90065c0eeb7f91977701] (Linaro GCC 7.3-2018.05) ) #1 SMP PREEMPT Thu Apr 11 20:39:46 CST 2019`
Docker : `Docker version v18.09.2, build v18.09.2`

使用debian/ubuntu不改端口默认，一直提示在创建。

debian改了默认端口均为8088，直接日志`standard_init_linux.go:207: exec user process caused "exec format error"`

**Comment by zf1976** [comment]
ARM64?

**Comment by Tamshen** [comment]
> ARM64?

对的 ARM

**Comment by zf1976** [comment]
> > ARM64?
> 
> 对的 ARM

等我明天抽空做镜像，现在做的都是x86

**Comment by zf1976** [comment]
> > ARM64?
> 
> 对的 ARM

debian tag的镜像支持arm64了，你现在可以拉下来跑

**Comment by Tamshen** [comment]
> debian tag的镜像支持arm64了，你现在可以拉下来跑

部署成功了，正常了
